### ISSUE TITLE
Negative anomaly map values

### ISSUE THREAD

**Issue by pietro-nardelli** [shyam671/Mask2Anomaly-Unmasking-Anomalies-in-Road-Scene-Segmentation#3]
Dear authors, 
congratulations for your great work!

I was using your method in inference mode and I realized that the visualization of the anomaly map values sometimes contains some red spots that can be treated as anomaly:

![image](https://github.com/shyam671/Mask2Anomaly-Unmasking-Anomalies-in-Road-Scene-Segmentation/assets/20285899/f786a1ed-9ed4-41ab-b4c7-fcf55c78b248)

By analyzing them, we can understand that they are negative values resulting from `anomaly_map = 1 - torch.max(anomaly_map[0:19,:,:], axis = 1)[0]`. Probably the `cv2.applyColorMap` is not able to correctly map negative values. Thus, to improve the visualization (and deleting red spots), **does it make sense to normalize those anomaly score values between 0 and 1** before using `cv2.applyColorMap`? See the image result:

![image](https://github.com/shyam671/Mask2Anomaly-Unmasking-Anomalies-in-Road-Scene-Segmentation/assets/20285899/dba24f0b-8440-4b63-955f-28a350e49dfb)

Additional question: **why, in the first place, do we have > 1 values in `outputs["sem_seg"]`** where  `outputs = predictor(im)`? I am assuming that the values should be between [0, 1] since they are the output of $softmax(C)^T \times sigmoid(M)$ and `anomaly_map = 1 - torch.max(anomaly_map[0:19,:,:], axis = 1)[0]` should represents the $f(x)$ in equation (2) of the paper. 

Thank you so much in advance for your answers!

**Comment by shyam671** [comment]
Hi Pietro,

Thank you for taking an interest in the work.

A) Yes, normalizing can give you better qualitative results. Although, It could hurt the AuPRC and FPR95.
B) Ideally, as you said, it shouldn't be more than 1. However, I have seen in some methods that clip values greater than 1. Maybe it's worth trying and see the results.

-Shyam
