### ISSUE TITLE
about prediction result

### ISSUE THREAD

**Issue by brianhu0716** [shyam671/Mask2Anomaly-Unmasking-Anomalies-in-Road-Scene-Segmentation#4]
Hi, I'm appreciate you to share this great work. However, during process, a problem occur with the model prediction results seems to have label '255', which leads to error reported when we need to calculate confusion matrix(34 * 34).  

My question is in the cityscapes dataset pre-process stage,  should I need to do any other work except the following command you mentioned in README:
CITYSCAPES_DATASET=/path/to/abovementioned/cityscapes python cityscapesscripts/preparation/createTrainIdLabelImgs.py

or this error occurs due to other issues? hope that you can share your opnions, very thanks!

**Comment by shyam671** [comment]
Hi,
Yes. We need to follow the same set of instructions given in cityscapes repo to prepare semantic segmentation dataset.

The confusion matrix takes values between 0 and 1. So we avoid the 255 label. More details regarding this can be found in anomaly_utils folder.
