### ISSUE TITLE
Could a license be added to the repo?

### ISSUE THREAD

**Issue by pdejorge** [shyam671/Mask2Anomaly-Unmasking-Anomalies-in-Road-Scene-Segmentation#5]
Dear authors, it would be very convenient if you add a LICENSE to your repository. This would allow third parties to build on your code and release it in a modified way. Note that without a LICENSE, it should not be possible to use the software as "open source". See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by shyam671** [comment]
Thanks for the suggestion. I have added the license.
