### ISSUE TITLE
strange result

### ISSUE THREAD

**Issue by Durobert** [shyam671/Mask2Anomaly-Unmasking-Anomalies-in-Road-Scene-Segmentation#7]
Hi, I followed the README to run the code. But the stage2 loss didn't decrease, and the result is very strange.what's the problem?
![20240111-213117](https://github.com/shyam671/Mask2Anomaly-Unmasking-Anomalies-in-Road-Scene-Segmentation/assets/13628621/d5cd3f8d-96c5-4863-bae9-d1948f14c1fd)

**Comment by shyam671** [comment]
Dear Durobert,

Thank you for your interest.
I have attached the link for the model along with ood_dataset(MS-coco processed subset).
Link: https://drive.google.com/drive/folders/1RRA_0eU2KZMNFGOTvSAdHaFl5B6L_MO8?usp=share_link

Can you please try from here.

Regards,
Shyam Nandan Rai
