### ISSUE TITLE
validation dataset is unavailable 

### ISSUE THREAD

**Issue by mehdifarhadi97** [shyam671/Mask2Anomaly-Unmasking-Anomalies-in-Road-Scene-Segmentation#9]
Hello, validation dataset removed today , I need it ! it had been available before 4 hours ago. 
could you mind make it available ?  ?
thanks

**Comment by shyam671** [comment]
Hi,
Here is the updated link:
https://drive.google.com/drive/folders/1eQhmPbKSZrN1AsieY9KFchfll7XC1_SF?usp=share_link

I was just freeing some space.

-Shyam
